### ISSUE TITLE
Pass data to popup

### ISSUE THREAD

**Issue by cliffgr** [evnaz/ENPopUp#7]
UIViewController *vc ;
        popup *myViewController ;
          myViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"PopUp"];
        myViewController.view.frame = CGRectMake(0, 0, 270.0f, 300.0f);
        myViewController.TESTSS=@"MALAKA";
        vc=myViewController;
        [self presentPopUpViewController:myViewController];

**Comment by richard182** [comment]
it doesn't work :(
